<div id='top'/>
# <center>Lesson 2: Logical Operators and Data Types</center>

More information on today's topics here:
https://docs.python.org/3.5/library/stdtypes.html

<div id='id-type'/>
## Comparison

Comparing numbers in Python is quite straightforward. 

In [1]:
x = 2

In [2]:
x > 1   

True

In [3]:
x < 1

False

In [4]:
x == 2  # "equal to"

True

In [5]:
x != 2 # "different from"

False

You can also chain arbitrarily long comparisons, but it can easily make your code hard to read.

In [6]:
1 < 2 < 3 < 4 < 5 < 6 < 7

True

In [7]:
1 < 2 < 3 < 4 > 5 < 6 < 7

False

<div id='id-type'/>
## Logical operators

You can also pass truth values through logical operators

In [8]:
x = 2
y = 5

In [9]:
(x == 2) and (y == 5)

True

In [10]:
(x == 2) or (y == 7)

True

In [11]:
(x == 0) or (y == 5)

True

In [12]:
not (x == 2)

False

You can actually store output of a logical statement in a variable

In [15]:
x = 10
y = 5
z = x > y
print("Z =", z)

Z = True


What kind of data is the returned truth value? It is called a **boolean** data type. More on this in the next section.

---

<div id='id-type'/>
## Objects and types


Every time you assign a name to a value the Python interpreter creates an `object`.

An `object` is a chunk of your computer's memory storing some **data** and built-in functions called **methods**. 

Everything is easier to explain by example, so let's dive into it.

### **bool**

A bool is one bit of information (0 or 1) that encodes truth values. 

To distinguish it from integers, in Python we write `False` (for 0) and `True` (for 1).

In [16]:
x = True
y = False
z = x and y

print(z)

False


In [17]:
type(x)

bool

<div id='id-int'/>
### int

An `int` is an integer: a number with no decimal points. Here's an `int`.

In [18]:
a = 3

In [19]:
type(a)

int

By the way, you can check the `type` of anything using the function `type`.

In [20]:
type(a)

int

<div id='id-float'/>
### float

These are slightly more interesting. They're numbers *with* decimal points. 

In [23]:
b = 3.1415

In [24]:
type(b)

float

Why do you think we need to distinguish between `int`s and `float`s?

In [26]:
2.0**5000 # This is why. Try 2*5000 instead

OverflowError: (34, 'Result too large')

<div id='id-str'/>
### str

`str` stands for "string". They're used to denote a bunch of text characters *strung* together. You can create strings by enclosing values in double or single quotes.

In [27]:
s = "This is a string"
type(s)

str

In [29]:
s1 = "a"
s2 = "b"
s1 * 10

'aaaaaaaaaa'

In [30]:
s = "abc"
s * 12

'abcabcabcabcabcabcabcabcabcabcabcabc'

#### NoneType

Consider this function. What is wrong with it?

In [42]:
def double(x):
    z = 2*x

If I do this, what is the value of y?

In [43]:
y = double(2)

In [44]:
w = 2 * y

TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

In [41]:
type(y), y

(NoneType, None)

<div id='id-list'/>
### list

`list`s contain an arbitrary number of values. You can create lists using square brackets.

In [45]:
cities = ["Sao Paulo", "Tokyo", "Vancouver", "Boston"]  # list of str
numbers = [14, 16, 20, 99, 42]  # list of int
things = ["hey", 1, "this", 2, "is", 3.0, "fun", 100]  # list of mixed stuff

In [47]:
emptylist = []

In [48]:
emptylist

[]

You can retrieve the $n^{th}$ item in a list by typing `[n]` after the name of the variable.

In [49]:
cities[1]

'Tokyo'

In [50]:
numbers[4]

42

In [51]:
things[0]

'hey'

<font size=6>&#9760;</font> In Python, the items in a collection of $n$ things are are numbered from 0 to $n-1$.

You can concatenate lists using +

In [52]:
["a","b","c"] + [1,2,3]

['a', 'b', 'c', 1, 2, 3]

Multiplication is repetition

In [53]:
["a", "b", "c"] * 5

['a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c']

<div id='id-array'/>
## numpy arrays

Lists are great to store things, but we can't do math with them. For that, we need the `array` type from the `numpy` package.

In [54]:
from numpy import array

We create `array`s by feeding a `list` of numbers to the function `array`.

In [55]:
a = array([1, 2, 3, 4, 5, 10])
print(a)

[ 1  2  3  4  5 10]


In [56]:
type(a)

numpy.ndarray

Here's some operations we can do with arrays.

In [59]:
b = a + 3  # Sum 3 to each element
print(b)

[ 4  5  6  7  8 13]


In [60]:
c = a**3  # Raise every element to the 3rd power
print(c)

[   1    8   27   64  125 1000]


There are many useful functions in the `numpy` package.

In [61]:
from numpy import sqrt, log, max, mean
from numpy.random import uniform

In [62]:
root_a = sqrt(a)
print(root_a)

[ 1.          1.41421356  1.73205081  2.          2.23606798  3.16227766]


In [63]:
log_a = log(a)
print(log_a)

[ 0.          0.69314718  1.09861229  1.38629436  1.60943791  2.30258509]


In [64]:
max_a = max(a)
print(max_a)

10


In [65]:
avg = mean(a)  
print(avg)

4.16666666667


It might not be very clear right now, but we're learning all of this so that we can do simulations.

In [68]:
u = uniform(low = 0, high = 10, size = 1000) # 1000 random numbers uniformly-distributed btw 0 and 1
mean(u)

4.9714529103008278

In [69]:
from numpy.random import randint

---

In [73]:
s = "this course goes until 3:50 pm today"

In [86]:
ss = s.split(" ")

In [82]:
a = array([1,2,3,4,5,33,-200,1,1,2,3,231])

In [83]:
a.cumsum()

array([   1,    3,    6,   10,   15,   48, -152, -151, -150, -148, -145,
         86])

In [84]:
a.mean()

7.166666666666667

In [85]:
a.min()

-200

<div id='id-methods'/>
## Methods

A `method` is a built-in function that comes with a type. After you define a variable, try accessing the available methods by typing "." and then TAB.

For example, here are some methods associated with the type `str`.

In [87]:
s = "ECON1151 is killing me"

In [89]:
s_replaced = s.replace("killing", "thrilling") # replaces first argument by second
print(s_replaced)

ECON1151 is thrilling me


In [90]:
words = s.split()  # splits a str at whitespace, and makes a list of words
print(words)

['ECON1151', 'is', 'killing', 'me']


Similarly, here are some associated with `list`

In [115]:
cities.append("New York")
print(cities)

['Sao Paulo', 'Tokyo', 'Vancouver', 'Boston', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York']


In [116]:
cities.reverse()
print(cities)

['New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'Boston', 'Vancouver', 'Tokyo', 'Sao Paulo']


In [117]:
cities.sort()
print(cities)

['Boston', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'New York', 'Sao Paulo', 'Tokyo', 'Vancouver']


<div id='id-tip'/>
<center>
<font color="red">Pro tip</font>
<br>
Don't try to memorize every method associated with every type. 
<br>
That wouldn't be fun. 
<br>
If you're not having fun, either I'm doing something wrong, or you are.
<br><br>
<font size = 1 ,align ="right">It's probably you.</font>
</center>